export const metadata = {
  title: "About | ScentProtocol",
  description: "The world's first digital perfume house on the blockchain",
};

export default function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto py-16 px-4">
      <h1 className="text-4xl font-bold mb-8 bg-gradient-to-r from-amber-300 to-rose-500 bg-clip-text text-transparent">
        About ScentProtocol
      </h1>

      <div className="space-y-6 text-white/80 leading-relaxed">
        <p>
          ScentProtocol is the world&apos;s first digital perfume house built entirely on-chain.
          Every fragrance is a unique ERC-721 NFT — a digital certificate of ownership for an
          AI-generated formula that can never be replicated.
        </p>

        <h2 className="text-2xl font-semibold text-amber-400 mt-8 mb-4">The Vision</h2>
        <p>
          We believe luxury should be borderless, verifiable, and eternal. By minting a Scent NFT,
          you own a one-of-a-kind formula generated by on-chain randomness — no two scents are ever
          the same.
        </p>

        <h2 className="text-2xl font-semibold text-amber-400 mt-8 mb-4">Built on Arc</h2>
        <p>
          Arc&apos;s sub-second finality and USDC-native gas make minting seamless. No ETH needed,
          no long waits — just pure digital perfumery.
        </p>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-10">
          {[
            { label: "Unique Formulas", value: "100%" },
            { label: "Finality", value: "<1s" },
            { label: "Notes Per Scent", value: "9" },
            { label: "Rarity Tiers", value: "4" },
          ].map((s) => (
            <div key={s.label} className="glass-card p-4 text-center">
              <div className="text-2xl font-bold text-amber-400">{s.value}</div>
              <div className="text-xs text-white/50 mt-1">{s.label}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
